### PR TITLE
Fix search screen empty query response

### LINKED ISSUE #62: [UI/VM] Search Screen has weird empty / starting behavior.
## Description:

1. Search screen immediately shows pending. It should be empty.
2. Search screen, if you type some stuff and delete it, shows ALL listings. it should be empty in this case.

### PR DESCRIPTION
**Pull request by caleb-bit**
## Overview

Originally, the search screen showed a loading screen when the user entered it, and any empty query after some nonempty query would result in all listings being displayed. This change makes both cases show a blank screen.

## Related PRs or Issues

Fixes #62 

## Screenshots
[Search Screen.webm](https://github.com/user-attachments/assets/f4dd61fc-0896-424f-946d-2c4e4fb474fb)

### CODE REVIEW

File: app/src/main/java/com/cornellappdev/resell/android/viewmodel/SearchViewModel.kt [hunk 1]
```diff
@@ -52,10 +52,14 @@ abstract class SearchViewModel(
...
-                if (stateValue().query == query) {
-                    applyMutation { copy(listings = ResellApiResponse.Success(response)) }
+                if (query == "") {
+                    applyMutation { copy(listings = ResellApiResponse.Success(listOf())) }
+                } else {
+                    val response = searchRepository.searchPostByUser(stateValue().uid, query)
+                    // By this time, the query may have changed. If so, ignore.
+                    if (stateValue().query == query) {
+                        applyMutation { copy(listings = ResellApiResponse.Success(response)) }
+                    }
```
Comment (zachseidner1) [inline app/src/main/java/com/cornellappdev/resell/android/viewmodel/SearchViewModel.kt:62]: This works but there are some things you could do to clean it up:
Use `isEmptyOrBlank` over `== ""` to check whether we should search.

We want our `try` `catch` blocks to be as small as possible. We also shouldn't set the state to loading and then immediately set it to success if the user's query is blank. So instead we should check for this earlier, outside of the `try` `catch`. We should only update it to pending if they have a query that is not empty or blank. 

Also, you can make this more readable by using `emptyList()` instead of `listOf()`

**Review by zachseidner1 — COMMENTED** [review]
Nice job with this, but there are some ways you could clean it up.

**Review by zachseidner1 — APPROVED** [review]
awesome! 🥳

File: app/src/main/java/com/cornellappdev/resell/android/viewmodel/SearchViewModel.kt [hunk 2]
```diff
@@ -43,23 +43,26 @@ abstract class SearchViewModel(
...
-            }
-            try {
-                val response = searchRepository.searchPostByUser(stateValue().uid, query)
-                // By this time, the query may have changed. If so, ignore.
-                if (stateValue().query == query) {
-                    applyMutation { copy(listings = ResellApiResponse.Success(response)) }
+        if (query.isEmpty() || query.isBlank()) {
+            applyMutation { copy(listings = ResellApiResponse.Success(emptyList())) }
+        } else {
+            // Try to fetch listings from backend
```
Comment (thisjustin123) [inline app/src/main/java/com/cornellappdev/resell/android/viewmodel/SearchViewModel.kt:49]: Instead of wrapping everything here in an `else`, just to reduce indentation, let's make the `if` body `return`. Then, delete the `else`. The body then will only run if the if does not return.

I think reducing indentation like this when possible is good :-)

**Review by thisjustin123 — CHANGES_REQUESTED** [review]
Tiny small suggestion. The PR looks fantastic though!

**Review by thisjustin123 — APPROVED** [review]
Love it. 🚀
